signalerPresence:
    path:   /signaler-presence
    defaults: { _controller: UtilisateurBundle:SignalerPresence:signalerPresence }

validerCours:
    path:   /valider-cours
    defaults: { _controller: UtilisateurBundle:ValiderCours:validerCours }

creerFeuillePresence:
    path:   /creer-feuille-presence
    defaults: { _controller: UtilisateurBundle:CreerFeuillePresence:creerFeuillePresence }

historiqueAbsence:
    path:   /historique-absence
    defaults: { _controller: UtilisateurBundle:VisionnerHistoriqueAbsence:visionnerHistoriqueAbsence }

accueilRespCFA:
    path:   /accueil-respCFA
    defaults: { _controller: UtilisateurBundle:SignalerPresence:signalerPresence }

accueilSecretaire:
    path:   /accueil-secretaire
    defaults: { _controller: UtilisateurBundle:SignalerPresence:signalerPresence }

historiqueFeuillePresence:
    path:   /historique-feuille-presence
    defaults: { _controller: UtilisateurBundle:HistoriqueFeuillePresence:historiqueFeuillePresence }

visionnerFeuillePresence:
    path:   /visionner-feuille-presence
    defaults: { _controller: UtilisateurBundle:VisionnerFeuillePresence:visionnerFeuillePresence }

profil:
    path:   /profil
    defaults: { _controller: UtilisateurBundle:Profil:profil }

contact:
    path:   /contact
    defaults: { _controller: UtilisateurBundle:Contact:contacter }