signaler_presence:
    path:   /signaler-presence/{leCours}
    defaults: { _controller: UtilisateurBundle:Cours:signalerPresence, leCours:null }
    requirements:
                leCours: \d+

signaler_absence_enseignant:
    path:   /signaler-absence-enseignant/{leCours}
    defaults: { _controller: UtilisateurBundle:Cours:signalerAbsenceEnseignant, leCours:null }
    requirements:
                leCours: \d+

valider_cours:
    path:   /valider-cours
    defaults: { _controller: UtilisateurBundle:Cours:validerCours }

creer_feuille_presence:
    path:   /creer-feuille-presence
    defaults: { _controller: UtilisateurBundle:FeuillePresence:creerFeuillePresence }

historique_absence:
    path:   /historique-absence
    defaults: { _controller: UtilisateurBundle:Cours:visionnerHistoriqueAbsence }

historique_absence_promos:
    path:   /historique-absence_promos
    defaults: { _controller: UtilisateurBundle:FeuillePresence:visionnerHistoriqueAbsencesPromos }

historique_facture:
    path:   /historique-factures
    defaults: { _controller: UtilisateurBundle:FeuillePresence:visionnerHistoriqueFacture }

historique_feuille_presence:
    path:   /historique-feuilles-presence
    defaults: { _controller: UtilisateurBundle:FeuillePresence:historiqueFeuillePresence }

visionner_feuille_presence:
    path:   /visionner-feuille-presence
    defaults: { _controller: UtilisateurBundle:FeuillePresence:visionnerFeuillePresence }

visionner_details_heures:
    path:   /visionner-details-heures
    defaults: { _controller: UtilisateurBundle:Cours:visionnerDetailsHeures }

profil:
    path:   /profil
    defaults: { _controller: UtilisateurBundle:Profil:profil}

contact:
    path:   /contact
    defaults: { _controller: UtilisateurBundle:Contact:contacter }

getEnseignantPourMatiere:
    path:   /getEnseignantPourMatiere
    defaults: { _controller: UtilisateurBundle:FeuillePresence:getEnseignantPourMatiere }
    methods: [post]