services:
#    utilisateur.example:
#        class: UtilisateurBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    ets:
        class:      UtilisateurBundle\Service\ETSService
        arguments:  [@doctrine.orm.entity_manager]

    absenceEtu:
            class:      UtilisateurBundle\Service\AbsenceService
            arguments:  [@doctrine.orm.entity_manager]