accueil_admin:
    path:   /accueil-admin
    defaults: { _controller: AdministrateurBundle:Accueil:accueil }

liste_promotions:
    path:   /liste-promotions
    defaults: { _controller: AdministrateurBundle:GestionPromotion:listePromos }

gerer_promotion:
    path:   /gerer-promotion
    defaults: { _controller: AdministrateurBundle:GestionPromotion:gestionPromo }

gerer_personnel:
    path:   /gerer-personnel
    defaults: { _controller: AdministrateurBundle:GestionPersonnel:listePersonnel }