accueil_admin:
    path:   /accueil-admin
    defaults: { _controller: AdministrateurBundle:Accueil:accueil }

liste_promotions:
    path:   /liste-promotions
    defaults: { _controller: AdministrateurBundle:GestionPromotion:listePromos }

gerer_promotion:
    path:   /gerer-promotion
    defaults: { _controller: AdministrateurBundle:GestionPromotion:gestionPromo }

ajouter_promo:
    path:   /ajouter-promo
    defaults: { _controller: AdministrateurBundle:GestionPromotion:ajoutPromo }

ajouter_etudiant:
    path:   /ajouter-etudiant
    defaults: { _controller: AdministrateurBundle:GestionPromotion:ajoutEtudiant }

ajouter_matiere:
    path:   /ajouter-matiere
    defaults: { _controller: AdministrateurBundle:GestionPromotion:ajoutMatiere }

gerer_personnel:
    path:   /gerer-personnel
    defaults: { _controller: AdministrateurBundle:GestionPersonnel:listePersonnel }