accueil_admin:
    path:   /accueil-admin
    defaults: { _controller: AdministrateurBundle:Accueil:accueil }

liste_promotions:
    path:   /liste-promotions
    defaults: { _controller: AdministrateurBundle:GestionPromotion:listePromos }

gerer_promotion:
    path:   /gerer-promotion/{id}
    defaults: { _controller: AdministrateurBundle:GestionPromotion:gestionPromo, id:null }
    requirements:
        id: \d+

ajouter_promo:
    path:   /ajouter-promo
    defaults: { _controller: AdministrateurBundle:GestionPromotion:ajoutPromo }

ajouter_etudiant:
    path:   /ajouter-etudiant/{id}
    defaults: { _controller: AdministrateurBundle:GestionPromotion:ajoutEtudiant }
    requirements:
            id: \d+

modifier_etudiant:
    path:   /modifier-etudiant/{id}
    defaults: { _controller: AdministrateurBundle:GestionPromotion:modificationEtudiant }
    requirements:
            id: \d+

ajouter_matiere:
    path:   /ajouter-matiere/{id}
    defaults: { _controller: AdministrateurBundle:GestionPromotion:ajoutMatiere }
    requirements:
        id: \d+

modifier_matiere:
    path:   /modifier-matiere/{id}
    defaults: { _controller: AdministrateurBundle:GestionPromotion:modificationMatiere }
    requirements:
        id: \d+

modifier_promo:
    path:   /modifier-promotion/{id}
    defaults: { _controller: AdministrateurBundle:GestionPromotion:modificationPromotion }
    requirements:
        id: \d+

gerer_personnel:
    path:   /gerer-personnel
    defaults: { _controller: AdministrateurBundle:GestionPersonnel:listePersonnel }

ajouter_personnel:
    path:   /ajouter-personnel
    defaults: { _controller: AdministrateurBundle:GestionPersonnel:ajoutPersonnel }

modifier_personnel:
    path:   /modifier-personnel/{id}
    defaults: { _controller: AdministrateurBundle:GestionPersonnel:modificationPersonnel }
    requirements:
        id: \d+